- hosts: F5
  connection: httpapi

  tasks:
    - name: Create Pool
      uri:
        follow_redirects: none
        validate_certs: false
        return_content: yes
        url: https://10.1.117.22/mgmt/tm/ltm/pool
        method: POST
        body:  
          name: "pool_ansible"
          monitor: "/Common/gateway_icmp"
          partition: "Common"
        body_format: json
        headers:
          Authorization: "Basic YWRtaW46UEBzc3cwcmQxMjM="
          Accept: "application/json"
      register: __result
    - name: Create Node
      debug:
        var: __result.content
